//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzBuildDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionSiteDiaryEntry
    {
        public int IDConstructionSiteDiary { get; set; }
        public string DiaryEntry { get; set; }
        public System.DateTime DiaryEntryDate { get; set; }
        public int DiaryEntryEmployeeID { get; set; }
        public int ConstructionSiteID { get; set; }
    
        public virtual ConstructionSite ConstructionSite { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
