//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzBuildDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHour
    {
        public int IDEmployeeHours { get; set; }
        public short HoursWorked { get; set; }
        public System.DateTime DateWorkDone { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
